-- Ejecuta este código en el "SQL Editor" de tu proyecto en Supabase para crear las tablas necesarias.

-- 1. Tabla de Productos (Inventario)
CREATE TABLE public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  stock integer default 0,
  price numeric default 0,
  status text not null,
  supplier text,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS para que sea pública por ahora (ya que no hay login estricto con Supabase Auth aún)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Products" ON public.products FOR ALL USING (true);


-- 2. Tabla de Usuarios del Sistema
CREATE TABLE public.app_users (
  id bigint generated by default as identity primary key,
  name text not null,
  cedula text unique not null,
  email text unique not null,
  role text not null,
  status text not null default 'Activo',
  last_login text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access App Users" ON public.app_users FOR ALL USING (true);


-- 3. Tabla de Facturas (Billing)
CREATE TABLE public.invoices (
  id text primary key, -- ej: FAC-17124151
  client text not null,
  cedula text not null,
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  total numeric not null,
  status text not null default 'Pagada',
  items_count integer not null,
  items jsonb -- para guardar los detalles de la venta (carrito)
);

ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Invoices" ON public.invoices FOR ALL USING (true);


-- 4. Inserción de Datos Iniciales (Opcional - para no tener el sistema vacío)
INSERT INTO public.products (name, category, stock, price, status, supplier, image)
VALUES 
  ('Fertilizante NPK 20kg', 'Fertilizantes', 45, 25.99, 'En Stock', 'AgroSupplies S.A.', '/fertilizer-bag.png'),
  ('Semillas de Maíz Premium', 'Semillas', 8, 15.50, 'Stock Bajo', 'Semillas del Valle', '/corn-seeds-bag.jpg'),
  ('Herbicida Glifosato 1L', 'Pesticidas', 23, 12.75, 'En Stock', 'QuímicaAgro Ltda.', '/herbicide-bottle.jpg');

INSERT INTO public.app_users (name, cedula, email, role, status, last_login)
VALUES
  ('Juan Pérez', '12345678', 'juan@triunfogo.com', 'Administrador', 'Activo', '2024-01-20'),
  ('María González', '87654321', 'maria@triunfogo.com', 'Vendedor', 'Activo', '2024-01-19');

INSERT INTO public.invoices (id, client, cedula, total, status, items_count)
VALUES
  ('FAC-001234', 'Juan Pérez', '12345678', 125.50, 'Pagada', 3),
  ('FAC-001235', 'María González', '87654321', 89.25, 'Pendiente', 2);
